### ISSUE TITLE
Validate profile boxes - user must fill out necessary ones

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#13]
User can fill out registration
User can fill out sign-in boxes
Registration boxes are marked as required if required
Registration boxes take in certain format for their info type
User can't submit without required boxes

**Comment by CoreyAR** [comment]
Phone number and zip code should be validated at minimum.

**Comment by CoreyAR** [comment]
Here is a table of the registration fields and validation.

| Field  | Type | Validation |
| ------------- | ------------- |------------- |
| First Name  | TextInput  | Required  |
| Last Name  | TextInput  | Required  |
| Phone |  Number | Valid Phone number |
| Email |  Number | Valid Email |
| Location |  Address Fields | Required|
| Organic |  Boolean | Required|
| Availability to schedule pickup (day of the week)  | Multiple choice (M/T/W/Th/F/Sa/Su)| Required|
| Availability to schedule pickup (time of day )  | Multiple choice (morning/ afternoon/ evening)| Required|

**Comment by CoreyAR** [comment]
Form validation logic was added to the jQuery app in this [PR](https://github.com/code-for-nashville/glean-tennessee-web/pull/50/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR171) 

We'll need to port that over to the React app once it is merged.
