### ISSUE TITLE
Use React

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#16]
Upgrade to React and possibly react-native to manage the UI

**Comment by combinatorist** [comment]
@Rian501, can you fill this out with a specific design so it's actionable?

It would require some rewriting so we would need some guidance one the plan. This should also be a high priority before fixing bugs or adding enhancements to prevent rework.

**Comment by CoreyAR** [comment]
Work for this has begun on the `feature/react-migrate` branch. @kevinahuber added details on his PR. https://github.com/code-for-nashville/glean-tennessee-web/pull/22

I marked it WIP while it is still being actioned on.

**Comment by CoreyAR** [comment]
We have deployed the react app! 🎉 https://glean-tennessee.firebaseapp.com/dashboard
