### ISSUE TITLE
Error handling on Sign In

### ISSUE THREAD

**Issue by CoreyAR** [code-for-nashville/glean-tennessee-web#18]
As a user, I should get helpful errors when logging in fails.

**Comment by combinatorist** [comment]
- What constitutes a valid login?
- Are we trying to help the user of the developer?
- What are some specific errors that need to be caught?

**Comment by CoreyAR** [comment]
This ticket is from the users perspective. We are using firebase for authentication and should start by surfacing the errors they are returning. If those errors are not helpful to the user, we should map the error codes to more helpful messages for the user.
