### ISSUE TITLE
Update Registration Form

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#42]
Add items missing from registration form (from the roadmap - Farmer Registers
The following fields must be available to register a new farmer

*name
*address
*phone
is_organic
availability schedule (for example, not available during CSA pickup)
additional notes)

**Comment by floatingman** [comment]
I can jump on this issue

**Comment by CoreyAR** [comment]
I believe this is a duplicate of #13 . I am going to close in favor of that ticket because it has more details.
