### ISSUE TITLE
Signup Form - Clicking label for checkbox toggles other checkbox, similar for radio inputs

### ISSUE THREAD

**Issue by enlore** [code-for-nashville/glean-tennessee-web#58]
To reproduce:

1. Start the signup process
2. Under "What days of the week are best for pickup?", click the label for "Tuesday"
3. Note that "Monday" is checked/unchecked

**Comment by enlore** [comment]
Same issue applies to input type radio as seen on the Submit a Request for Gleaners screen.

**Comment by rousell** [comment]
PR for this change: https://github.com/code-for-nashville/glean-tennessee-web/pull/59

**Comment by enlore** [comment]
Looks good. Leaving this open for a fix for the radio buttons as well.

**Comment by andrewleverette** [comment]
I’ve opened a pull request for this issue.
