### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#61]
(As a user in the react version, I am confused by the logo when I use the app on a computer screen.)

Currently, the favicon is set as the react logo.

It would be better to reset it to the SoSA logo (or something less confusing).

**Comment by mrswagbhinav** [comment]
Fixed the issue with PR https://github.com/code-for-nashville/glean-tennessee-web/pull/65

**Comment by Rian501** [comment]
(As with the other issue on your PR, this may be changed a bit with the react migration to be completed imminently)

**Comment by Rian501** [comment]
This was fixed in deploy-prep branch previous merged.
