### ISSUE TITLE
Unrequire address/directions in submission of glean request

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#64]
In the react version - Currently, a user is required to fill out the address/directions field in the form before submitting it.

Because their address is included in the profile that will be attached to the email, this field should be optional.

**Comment by andrewleverette** [comment]
I have a fix for this issue, i'm just not sure which branch to create a pull request for. Should this be merged into master or can we create a dev/enhancements branch as a staging area?

**Comment by andrewleverette** [comment]
I've created a pull request for this issue [here](https://github.com/code-for-nashville/glean-tennessee-web/pull/70).

**Comment by CoreyAR** [comment]
I agree that we should create a dev/ staging branch. We can take this into master as part of our first release and I'll cut a dev branch.
