### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#7]
- [x] App must be responsive to small screen size, mobile friendly.
- [x] User can hit the 'return/enter' key to sign in and to submit for gleaning from the text box, and to register from the zip code box

**Comment by andrewleverette** [comment]
I'm working on the second part of this issue, I may have this done by tomorrow.

**Comment by andrewleverette** [comment]
I've created a pull request for this issue [https://github.com/code-for-nashville/glean-tennessee-web/pull/69](url).
