### ISSUE TITLE
Indicate password issues more precisely

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#72]
When a person is signing up, they will get a notification that their password must be 8 characters long, even if it is long enough (but is presumably breaking a different rule).

As a user, I would like more specific information because it is frustrating to be told my password will not work because it must be at least 8 characters long (when it is in fact long enough).

**Comment by andrewleverette** [comment]
I’ll have a look at this tomorrow.

**Comment by Rian501** [comment]
Will be making a few more tickets to update password regex acceptance.
