### ISSUE TITLE
Progressive Web App for offline button clicks?

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#9]
--research possibilities

**Comment by CoreyAR** [comment]
I think we can use `create-react-app` and it will have works out of the box.

**Comment by combinatorist** [comment]
@Rian501, @CoreyAR, we need to discuss and finalize the strategy for this. Also, this issue seems related to #16 in terms of deciding tech stack, right?

**Comment by CoreyAR** [comment]
This will be covered once we switch to React. We are using create-react-app which supports service workers out of the box. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app

Work for this has begun on the `feature/react-migrate` branch.

**Comment by Rian501** [comment]
I know it supports service workers out of the box, but I'm not sure how to best utilize their functionality. This is something that will require more research (for me at least).
